#!/bin/sh

set -e

. ./terraform.conf

case "$ARCH" in
    amd64|i386)
        MIRROR_BINARY_URL="http://archive.ubuntu.com/ubuntu/"
        MIRROR_BINARY_SECURITY_URL="http://security.ubuntu.com/ubuntu/"
        ;;
    arm64)
        MIRROR_BINARY_URL="http://ports.ubuntu.com/ubuntu-ports/"
        MIRROR_BINARY_SECURITY_URL="http://ports.ubuntu.com/ubuntu-ports/"
        ;;
esac

lb config noauto \
    --architectures "$ARCH" \
    --mode debian \
    --initramfs none \
    --distribution "$BASECODENAME" \
    --parent-distribution "$BASECODENAME" \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --linux-packages none \
    --bootappend-live "boot=casper maybe-ubiquity quiet splash" \
    --debootstrap-options="--extractor=ar --keyring=/etc/apt/trusted.gpg" \
    --checksums md5 \
    --mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --mirror-chroot-security "$MIRROR_BINARY_SECURITY_URL" \
    --parent-mirror-chroot-security "$MIRROR_BINARY_SECURITY_URL" \
    --mirror-binary-security "$MIRROR_BINARY_SECURITY_URL" \
    --parent-mirror-binary-security "$MIRROR_BINARY_SECURITY_URL" \
    --mirror-binary "$MIRROR_BINARY_URL" \
    --parent-mirror-binary "$MIRROR_BINARY_URL" \
    --keyring-packages ubuntu-keyring \
    --apt-options "--yes --option Acquire::Retries=2 --option Acquire::http::Timeout=45" \
    --cache-packages false \
    --uefi-secure-boot enable \
    --binary-images iso-hybrid \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --firmware-binary false \
    --firmware-chroot false \
    --zsync false \
    --security true \
    "${@}"

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@CODENAME/$CODENAME/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

# T2 Linux
sed -i "s/@KERNEL/$KERNEL/" config/package-lists/desktop.list.chroot_install
sed -i "s/@KERNEL_HEADERS/$KERNEL_HEADERS/" config/package-lists/desktop.list.chroot_install
